### ISSUE TITLE
插件误转发 Quickshop 信息

### ISSUE THREAD

**Issue by Takeoff0518** [MakesYT/chatsync_bukkit#3]
Bukkit 插件版本：[V2.3.5-3](https://github.com/MakesYT/chatsync_bukkit/releases/tag/V2.3.5-3)

Mirai 插件版本：[V1.0.7](https://github.com/MakesYT/chatsync_mirai/releases/tag/V1.0.7)

服务端版本：Paper-1.18.2-388

Quickshop 版本：5.1.0.9

RT，使用 Quickshop 插件购买物品时输入聊天框的购买数量等信息，会被直接转发到 QQ。

**Comment by Maklith** [comment]
尝试 V2.3.5-4 版本

**Comment by Maklith** [comment]
> Bukkit 插件版本：[V2.3.5-3](https://github.com/MakesYT/chatsync_bukkit/releases/tag/V2.3.5-3)
> 
> Mirai 插件版本：[V1.0.7](https://github.com/MakesYT/chatsync_mirai/releases/tag/V1.0.7)
> 
> 服务端版本：Paper-1.18.2-388
> 
> Quickshop 版本：5.1.0.9
> 
> RT，使用 Quickshop 插件购买物品时输入聊天框的购买数量等信息，会被直接转发到 QQ。

问题解决了吗，解决了麻烦关闭issue

**Comment by Takeoff0518** [comment]
已更新版本 [2.3.5-5](https://github.com/MakesYT/chatsync_bukkit/releases/tag/V2.3.5-5)

[Quickshop-Remake 5.1.0.9](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/releases/tag/5.1.0.9) 测试失败，消息仍被转发

![](https://github.com/Takeoff0518/Takeoff0518/blob/7344303fd12844a00b44f06c3946a6838cb459f6/issue_temp/QQ%E6%88%AA%E5%9B%BE20230514002430.png?raw=true)

[5.1.2.0](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/releases/tag/5.1.2.0) 测试失败


[一种可能的解决方案](https://github.com/LinearBit/LinearBot/commit/994d080abd3aa1dce70018b80325139207376e13#diff-a0cf80e4c073a907a640371ee13d1cf99c3b6eec6d091f64560bb8f786a3f0f4)？（写个hook？）

**Comment by Maklith** [comment]
> 已更新版本 [2.3.5-5](https://github.com/MakesYT/chatsync_bukkit/releases/tag/V2.3.5-5)
> 
> [Quickshop-Remake 5.1.0.9](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/releases/tag/5.1.0.9) 测试失败，消息仍被转发
> 
> ![](https://github.com/Takeoff0518/Takeoff0518/blob/7344303fd12844a00b44f06c3946a6838cb459f6/issue_temp/QQ%E6%88%AA%E5%9B%BE20230514002430.png?raw=true)
> 
> [5.1.2.0](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/releases/tag/5.1.2.0) 测试失败
> 
> 
> [一种可能的解决方案](https://github.com/LinearBit/LinearBot/commit/994d080abd3aa1dce70018b80325139207376e13#diff-a0cf80e4c073a907a640371ee13d1cf99c3b6eec6d091f64560bb8f786a3f0f4)？（写个hook？）

这是一个quickshop的设计缺陷，他的监听器的优先级也是最低，不知道怎么想的，理论上他应该用高于正常的优先级，但是他用了最低很奇怪

**Comment by Maklith** [comment]
> 已更新版本 [2.3.5-5](https://github.com/MakesYT/chatsync_bukkit/releases/tag/V2.3.5-5)
> 
> [Quickshop-Remake 5.1.0.9](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/releases/tag/5.1.0.9) 测试失败，消息仍被转发
> 
> ![](https://github.com/Takeoff0518/Takeoff0518/blob/7344303fd12844a00b44f06c3946a6838cb459f6/issue_temp/QQ%E6%88%AA%E5%9B%BE20230514002430.png?raw=true)
> 
> [5.1.2.0](https://github.com/PotatoCraft-Studio/QuickShop-Reremake/releases/tag/5.1.2.0) 测试失败
> 
> [一种可能的解决方案](https://github.com/LinearBit/LinearBot/commit/994d080abd3aa1dce70018b80325139207376e13#diff-a0cf80e4c073a907a640371ee13d1cf99c3b6eec6d091f64560bb8f786a3f0f4)？（写个hook？）

>
你可以再试一下应该没问题了

**Comment by Takeoff0518** [comment]
插件已更新到 2.3.6，但是 Quickshop 消息仍然被转发。

测试方式与上图相同。

Quickshop 版本：5.1.2.0

难蚌

**Comment by Maklith** [comment]
> 插件已更新到 2.3.6，但是 Quickshop 消息仍然被转发。
> 
> 测试方式与上图相同。
> 
> Quickshop 版本：5.1.2.0
> 
> 难蚌

创建的消息会被转发，但是后续购买我测试了没问题的

**Comment by Takeoff0518** [comment]
> 创建的消息会被转发，但是后续购买我测试了没问题的

懂了，刚才我又试了一下，不停服再次重复一遍相同的操作就没有转发。但是通常服务端跑起来后第一次的操作消息都会被转发，无论是创建还是购买操作。

**Comment by Maklith** [comment]
>  > 创建的消息会被转发，但是后续购买我测试了没问题的
> 
> 懂了，刚才我又试了一下，不停服再次重复一遍相同的操作就没有转发。但是通常服务端跑起来后第一次的操作消息都会被转发，无论是创建还是购买操作。

我明天看看吧，你这个时差受不了😂

**Comment by Takeoff0518** [comment]
upd: Slimefun 菜单搜索物品的消息也被转发了

**Comment by Takeoff0518** [comment]
upd: Slimefun 菜单搜索物品的消息也被转发了

**Comment by Maklith** [comment]
> upd: Slimefun 菜单搜索物品的消息也被转发了

给我一个具体的示例吧,这个插件我找了半天没看到哪里用了chat

**Comment by Takeoff0518** [comment]
> > upd: Slimefun 菜单搜索物品的消息也被转发了
> 
> 给我一个具体的示例吧,这个插件我找了半天没看到哪里用了chat
<img src="https://raw.githubusercontent.com/Takeoff0518/Takeoff0518/ae18fb2595c38da6f26f672c2e5e16afa0f1ed08/issue_temp/QQ%E5%9B%BE%E7%89%8720230527164138.jpg" width="50%">

就是这玩意，点一下从聊天框搜东西
